apiVersion: v1
kind: Service
metadata:
  name: {{ include "leantraderbot.fullname" . }}
  labels:
    app: {{ include "leantraderbot.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "leantraderbot.name" . }}
    release: {{ .Release.Name }}

