timeframe: "1m"
fee_bps: 12
slippage_bps: 8
risk:
  initial_equity: 50
  risk_per_trade_bps: 0
  max_daily_loss_bps: 80
  max_open_positions: 2
  atr_period: 14
  atr_stop_mult: 2.2
  atr_trail_mult: 1.2
  fixed_stake_usd: 1.0
guards:
  cooldown_bars: 10
  max_loss_streak: 3
  daily_profit_lock_bps: 40
  spread_bps_threshold: 20
  max_trades_per_day: 20
universe:
  min_volume_usd: 1000000
  top_n: 4
  quote: "USDT"
  meme_only: true
  min_listing_days: 10
