symbols:
  - BTC/USDT
timeframe: "1m"
fee_bps: 10
slippage_bps: 3
risk:
  initial_equity: 50
  risk_per_trade_bps: 0
  max_daily_loss_bps: 80
  max_open_positions: 1
  atr_period: 14
  atr_stop_mult: 2.0
  atr_trail_mult: 1.3
  fixed_stake_usd: 1.5
strategy:
  ema_fast: 50
  ema_slow: 200
  bb_period: 22
  bb_std: 2.0
  bb_bandwidth_lookback: 120
  bb_bandwidth_quantile: 0.5
guards:
  cooldown_bars: 5
  max_loss_streak: 3
  daily_profit_lock_bps: 40
  spread_bps_threshold: 8
  max_trades_per_day: 25
reports_dir: "reports"
cache_dir: "cache"
sizer:
  mode: fixed_usd           # fixed_usd | percent_equity | fixed_qty
  fixed_usd: 1.50           # used if mode=fixed_usd
  percent_equity: 1.0       # used if mode=percent_equity
  fixed_qty: 0.0            # used if mode=fixed_qty
  min_qty: 0.0
