services:
  metrics:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >-
      bash -lc "pip install -r requirements.txt || pip install --no-cache-dir fastapi uvicorn prometheus_client &&
      python -m observability.http_metrics --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - metrics

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_HOST_PORT:-3001}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
      - ./infra/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
