global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "leantraderbot"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "leantrader_local_metrics"
    static_configs:
      - targets: ["localhost:9000"]
