
version: "3.9"
services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
    volumes: ["redisdata:/data"]

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-leant}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-leantpass}
      POSTGRES_DB: ${POSTGRES_DB:-leantrader}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ..
    restart: unless-stopped
    env_file: ../.env
    command: uvicorn leantrader.api.app:app --host 0.0.0.0 --port 8000
    expose: ["8000"]
    depends_on:
      - redis
      - db
    volumes:
      - ../data:/app/data
      - ../:/app

  agents:
    build: ..
    restart: unless-stopped
    env_file: ../.env
    command: >
      python -c "from leantrader.agents.market_scheduler import run_pairs; 
      run_pairs({'XAUUSD':'data/ohlc/XAUUSD_M15.csv','EURUSD':'data/ohlc/EURUSD_M15.csv','BTCUSDT':'data/ohlc/BTCUSDT_M15.csv'}, sleep_s=30)"
    depends_on:
      - api
      - redis
    volumes:
      - ../data:/app/data
      - ../:/app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api

volumes:
  redisdata:
  pgdata:
