name: CI

on:
  push:
    branches: [ main, master, 'feature/**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          python -m pip install pytest

      - name: Lint (flake8)
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 || true

      - name: Import smoke
        env:
          ENABLE_LIVE: 'false'
        run: |
          python - << 'PY'
          try:
              import importlib
              importlib.import_module('router')
              print('router import OK')
          except Exception as e:
              print('router import FAILED:', e)
              raise
          PY

      - name: Run tests (if any)
        env:
          ENABLE_LIVE: 'false'
        run: |
          if [ -d tests ]; then
            pytest -q || true
          fi
