name: Python tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest requests-mock
          fi
          pip install pytest
      - name: Run import check
        run: |
          python tools/import_check.py || true
      - name: Install dev deps (lint/mypy)
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy || true
      - name: Run linters (non-blocking)
        run: |
          flake8 . || true
          mypy . --ignore-missing-imports || true
      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest -q
