name: Simple Fix Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pytest numpy pandas httpx fastapi aiohttp
    
    - name: Ensure modules exist
      run: python ensure_modules.py
    
    - name: Run tests
      run: |
        export PYTHONPATH=.
        python -m pytest tests/test_confirm_flow.py -v
    
    - name: Success
      run: echo "✅ Tests passed!"